"""agregar is_favorite a searches

Revision ID: 5629fb820d3c
Revises: 7df5518c358d
Create Date: 2026-07-15 20:54:51.417354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5629fb820d3c'
down_revision: Union[str, Sequence[str], None] = '7df5518c358d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'searches',
        sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'is_favorite')
    # ### end Alembic commands ###
